### ISSUE TITLE
Need an example

### ISSUE THREAD

**Issue by rchastain** [salvadorbs/docxReplacer#1]
Hello!

Very interesting project.

Please could you provide an example, with a *.docx file, so we can easily figure what the program does, and how to use it?

By the way, would it be easy to add support for *.odt files?

Best regards.

Roland

**Comment by salvadorbs** [comment]
Hi,

with the latest commits I added a couple of example files and support for odt files.

The application is quite simple and with a handful of parameters. An example of a command is

```console
docxreplacer.exe --inputdoc="samplefile.odt" --outputdoc="newfile.odt" --placeholdersJson="test.json"
```

Parameters:
```console
The following command line options are valid:

--inputdoc=<file>  or -i                Filepath to input docx/odt
--placeholdersjson=<file>  or -p        Filepath to placeholders json file
--outputdoc=<file>  or -o               Filepath to output docx/odt (default: newDocx.docx)
```

**Comment by rchastain** [comment]
Thank you very much. Works perfectly here (Linux).

I close the issue.
